name = "Vanilla Patchcraft"
author = "xinchen"
version = "1.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d4f071d8bc703f456704627b6b201abb413055234ce498d21af0a30c30f99c1"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21.10"]
