name = "Vanilla Patchcraft"
author = "xinchen"
version = "1.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "23c90fd74bc3476b70c16f2f4986a9bed47365941f3418c0d43fbb84f5b7f105"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21.10"]
