name = "Vanilla Patchcraft"
author = "xinchen"
version = "1.1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e8fc189914ac3ffaffa607e0aa94cbb99eea1f6956fc066c2f60eec8bfa60906"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = []
