hash-format = "sha256"

[[files]]
file = "LICENSE"
hash = "a28da45eb8939df440d892454ba2a213a3e83846079484e34b3da4bc89f54799"

[[files]]
file = "bliss-shader.pw.toml"
hash = "756acba0fb870af603cae0a8d5f49118ca8e6f0a9d38ebd361fe43c187f7c2db"
metafile = true

[[files]]
file = "complementary-unbound.pw.toml"
hash = "006170836f3180d229a6b95e1b33c060d7afcd0755273669faf78e86f50579ed"
metafile = true

[[files]]
file = "config/appleskin.json5"
hash = "65edc28ca2bf6bd3e3684ae545fb74bcc0ec935a40d6ac60cb68c00c152e34fb"

[[files]]
file = "config/controlify.json"
hash = "5dc4f29febdf22dd04f2c119f265f279d4f79bfaca4e75ea2b31dec95461b348"

[[files]]
file = "config/crash_assistant/config.toml"
hash = "66b0b7615478d0da2fd331053b82ce72912b09fb7bf982a96124d27b290c8126"

[[files]]
file = "config/crash_assistant/crash_assistant_localization_overrides/README.md"
hash = "943e1c3672b8a03f27519b357091133205119c7b3db2fcc4c25b597cabf8926d"

[[files]]
file = "config/crash_assistant/modlist.json"
hash = "f5120fd6084999cc261b6a3dcc798123bb6739fe82536c2832325da3a7261e7a"

[[files]]
file = "config/crash_assistant/problematic_mods_config.json"
hash = "989fb8f797a5a894f0cbf8bf529ac20c88cceee72384bdbeedd6a22d455199a3"

[[files]]
file = "config/dynamic_fps.json"
hash = "ca3d163bab055381827226140568f3bef7eaac187cebd76878e0b63e9e442356"

[[files]]
file = "config/entityculling.json"
hash = "5110d83fa12df053d48eb3bcfded9d174e617910ce3e6c72f01dfc248c4e6abb"

[[files]]
file = "config/fabric/indigo-renderer.properties"
hash = "5f992f93f0e4d20250d9a66f4e55f641658faf44f27bd44dabd3b69fdd2f13b0"

[[files]]
file = "config/ferritecore.mixin.properties"
hash = "a2091a291309db8920c8a80e913ed31c24c29687d8cd25ac18076ad85a90ddb8"

[[files]]
file = "config/inventoryprofilesnext/integrationHints/exampleIntegrationHints.json"
hash = "ca413dea02cce69c69dccdc525fb0ec013236876eff2d142772c68db3d772d3a"

[[files]]
file = "config/inventoryprofilesnext/inventoryprofiles.json"
hash = "1894a44b24cd0b253b13917ebbc3d5eed36042c2a2bda0691e846e8ffae2a8f1"

[[files]]
file = "config/iris-excluded.json"
hash = "4d3264b58c502afaeca3f44e8d2db0843c54b8ba957afd21a2d450fe10dafefb"

[[files]]
file = "config/iris.properties"
hash = "f2e640a828b8955de0739eb62ae5819812ab563e5f2fb8c9222a7688aa2fc49d"

[[files]]
file = "config/jade/hide-blocks.json"
hash = "881bebe1f34ae249fc7d83f6a0d97ce3598746c133bc369775fc48fdeb5e1a76"

[[files]]
file = "config/jade/hide-entities.json"
hash = "4aa6e50e59ce75cc6e335e69ac98277f3d5afc1b016bb6c14aeece67a4ebb543"

[[files]]
file = "config/jade/hide-mob-effects.json"
hash = "a5c36f4ed48b1262f7f7d7be731c87c18aa6fdb79aaddb54568f9f8d526925c7"

[[files]]
file = "config/jade/jade.json"
hash = "343dd8cee5cfbb84ae0bae705436581742f049edc05c5a354154d3cec216b109"

[[files]]
file = "config/jade/profiles/1/jade.json"
hash = "2e8c2572c1df12ca4f150244f5de004f25c8ad6c3be039c3f10c9f47ae255e3e"

[[files]]
file = "config/jade/profiles/2/jade.json"
hash = "002297a25064edf501199d18d6b342037b991d0304fdbf4671640ca92dc1719e"

[[files]]
file = "config/jade/profiles/3/jade.json"
hash = "01bd23c0a15cd378b7e69f79264a8bf5f3f5b1d747f11519e498438c8a091b91"

[[files]]
file = "config/jade/server-plugin-overrides.json"
hash = "44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a"

[[files]]
file = "config/jade/sort-order.json"
hash = "c0235d429020dce0cd44eb11e34a728f83e8416ef5b61bd9607af370e963ad6c"

[[files]]
file = "config/journeymap-server.json"
hash = "2b77ff82093eb3698b79b2b953806855d1880d414544a8158f41b028d8e293ca"

[[files]]
file = "config/lithium.properties"
hash = "6cf6f83720071fd1657c8e79b357caf68d40f410ae123e5f922483eb1d1d25be"

[[files]]
file = "config/modmenu.json"
hash = "16d20c40cc6c114faff5493b561873fe160a65047720bc19fb3a3dd64aa67f3b"

[[files]]
file = "config/peek/peek.properties"
hash = "59742cd9cc067a7f42b9a402096569a8d33029a0e304ead3b31f2a5975b5bd7d"

[[files]]
file = "config/sodium-fingerprint.json"
hash = "8e4857de7cb27f8f8627bf8b73db6de3c57717b62a21163c5764923345101d41"

[[files]]
file = "config/sodium-mixins.properties"
hash = "b627c4456e6fa0bc4b5f85e2f1cd949faedae3cb9afdaf2a5f52e6f3b6ae1f01"

[[files]]
file = "config/sodium-options.json"
hash = "d3482af3895ad31a3b9c59b26807eb9944ede706b3d314668ad83c94d61bd195"

[[files]]
file = "config/yacl.json5"
hash = "121b93764159be6fb7dab523b29a844e2bb78400ce8c48f52135a097e9b0006e"

[[files]]
file = "journeymap/config/6.0/journeymap.core.config"
hash = "c2015acad049d4aa879dce8bd56dbbfcf7042835ee4810a79f24c4d6173a602d"

[[files]]
file = "journeymap/config/6.0/journeymap.fullmap.config"
hash = "0009487a2336cd67fd8b1ead68941211398473df56b431d08aa35527a34a0977"

[[files]]
file = "journeymap/config/6.0/journeymap.minimap.config"
hash = "e36b65324b7df58235a8faf0daf36647d089a3a76bc8907e6186e9f4ae3e1c9b"

[[files]]
file = "journeymap/config/6.0/journeymap.minimap2.config"
hash = "72f2a99309201c158e386e2d9b140d422854cd0410a2fa961daea736a42f488c"

[[files]]
file = "journeymap/config/6.0/journeymap.rendering.config"
hash = "59139373798af345188a9a11a0dd317ae39a5749d575cb0dbbfd481732c5caf7"

[[files]]
file = "journeymap/config/6.0/journeymap.topo.config"
hash = "2f6e8125fa9f35e0c700d49c908e0d60216d6d1cced17701351a174995570535"

[[files]]
file = "journeymap/config/6.0/journeymap.waypoint.config"
hash = "f592ac0ef3eb2791cc710d32e87df5ba6886d4e5d29c30250439d5147d13c778"

[[files]]
file = "journeymap/config/6.0/journeymap.webmap.config"
hash = "17fbf319709adeec6b71ead4ed0a2fc37210795257ab370c251ec36893c2253c"

[[files]]
file = "mods/appleskin.pw.toml"
hash = "1bf302009fc75c3519ea095753fe926af91b0a2dce732d1775fa1920aca8e56a"
metafile = true

[[files]]
file = "mods/controlify.pw.toml"
hash = "b1f5e7bdfbe821180a261b7b2ea2a37f20bdd2c13a2f435d664647f447f733b0"
metafile = true

[[files]]
file = "mods/crash-assistant.pw.toml"
hash = "dff41426a17ac8010ebcb69a15950bb824a3899684bdcd1a520e48f8f171ccbd"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "10916b552d45d65fbf872a5649c4d767cba25700b01e19918de0c0ae7962ba1c"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "f40522755246c7e247a3580bcd9b5e1a7ccea6c2133bcc686f7afe3aedaeb9ab"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "189134fe48404ea4f716f6ee705d5af668a493264c1af07b02ce18113b346de9"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "94f000249d21c4fc3b7744f9579bb6ac0d48e6bf4860fad16f23c997950a47f3"
metafile = true

[[files]]
file = "mods/ferritecore-fabric.pw.toml"
hash = "47a38ead307c2d86ac06e12f70847dc0194da9014608d4ac7b4133ae6a5abdda"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "c3b8abec750268c238b08e41f81b69da524064284f17f63ef055a3bcf3bac4f9"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "4ed061d122cb39f34ed730984c7bcf03437250f24a21975203bb4598d7d86a14"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "179047f50e0b2eb0fc669fded7c6a480441d7e8a0961453b2e21274c4d8f2e1c"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "c75fefbf0abf36da4f2de6e7da8d6988e9bc2301d0ada850755c86c5f315fe8e"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
hash = "b0d82cb639999d5e286f95c50932eda4c8609abcd1d62a8037d4fc4f86320c16"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "bcfd26bc56aa72b4edd5cd6a025137e51dc6cb4a7866a7665511009404d13bb9"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "5dd45d5fd5e1ae2bd521b93a70b83c69b57ada18f424c6562d8c6ea9980cfb3e"
metafile = true

[[files]]
file = "mods/peek.pw.toml"
hash = "408b30147b85fb7374298b26788813ef3442bff71f93fa049f3b9834ec44ffa5"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "e674752dd4dd07c33d9b94f6e19c15ef893c356c3c5ed77aeaf35cf6d2325130"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "279ea1bb4b776be9176fe34416e2132e37abfce4483def54177091cc0f2faade"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "cfa4ddfc8999e7be331c6dad1f2a0372f996243241d21697939e6838b3402c6d"
metafile = true

[[files]]
file = "options.txt"
hash = "554af6c8c0685c0e381ea8f0e9d84d039d29730439ed662ab676d06822c8855b"

[[files]]
file = "resourcepacks/faithful-64x.pw.toml"
hash = "702873e526e71f370d12145a660f6eefacb230323f7142664c79f218548e4024"
metafile = true
