hash-format = "sha256"

[[files]]
file = "LICENSE"
hash = "a28da45eb8939df440d892454ba2a213a3e83846079484e34b3da4bc89f54799"

[[files]]
file = "config/appleskin.json5"
hash = "65edc28ca2bf6bd3e3684ae545fb74bcc0ec935a40d6ac60cb68c00c152e34fb"

[[files]]
file = "config/crash_assistant/config.toml"
hash = "755e6ee75977c54dc22a3631822cd8adc8b4b57b49776432f67b41c8043a67fa"

[[files]]
file = "config/crash_assistant/crash_assistant_localization_overrides/README.md"
hash = "52f394cd3754a29a6f236b1fe622bb430fa7e4632bce262eeb0333d71842bb52"

[[files]]
file = "config/crash_assistant/modlist.json"
hash = "4a6be59e11c56860e8a3499946c0aeec078c4c92178f6f35d9f42b26b34fa095"

[[files]]
file = "config/crash_assistant/problematic_mods_config.json"
hash = "989fb8f797a5a894f0cbf8bf529ac20c88cceee72384bdbeedd6a22d455199a3"

[[files]]
file = "config/dynamic_fps.json"
hash = "ca3d163bab055381827226140568f3bef7eaac187cebd76878e0b63e9e442356"

[[files]]
file = "config/dynamiccrosshair.json5"
hash = "99458f0109609cff4e0c6f3afb3ba474865784321f1d6625311dceb6ff55fae2"

[[files]]
file = "config/entityculling.json"
hash = "5110d83fa12df053d48eb3bcfded9d174e617910ce3e6c72f01dfc248c4e6abb"

[[files]]
file = "config/fabric/indigo-renderer.properties"
hash = "4b834d625f5e90a872297c248ad92d09c53b60a0cc8b11849b1b82be173ce5d2"

[[files]]
file = "config/ferritecore.mixin.properties"
hash = "a2091a291309db8920c8a80e913ed31c24c29687d8cd25ac18076ad85a90ddb8"

[[files]]
file = "config/inventoryprofilesnext/integrationHints/exampleIntegrationHints.json"
hash = "ca413dea02cce69c69dccdc525fb0ec013236876eff2d142772c68db3d772d3a"

[[files]]
file = "config/inventoryprofilesnext/inventoryprofiles.json"
hash = "3d0b10cb2ffcd8d24d9f719f2f0e9f6f40b11d31f6854e4a34a272fa59944872"

[[files]]
file = "config/iris-excluded.json"
hash = "4d3264b58c502afaeca3f44e8d2db0843c54b8ba957afd21a2d450fe10dafefb"

[[files]]
file = "config/iris.properties"
hash = "bcdad57b94a51caa3a31d81f1eaf8da7959ac790309c938adc57024c3dd8d2ca"

[[files]]
file = "config/jade/hide-blocks.json"
hash = "881bebe1f34ae249fc7d83f6a0d97ce3598746c133bc369775fc48fdeb5e1a76"

[[files]]
file = "config/jade/hide-entities.json"
hash = "4aa6e50e59ce75cc6e335e69ac98277f3d5afc1b016bb6c14aeece67a4ebb543"

[[files]]
file = "config/jade/hide-mob-effects.json"
hash = "a5c36f4ed48b1262f7f7d7be731c87c18aa6fdb79aaddb54568f9f8d526925c7"

[[files]]
file = "config/jade/jade.json"
hash = "c94f198c6ce5ccbe9e8eafb3e62b366294dd605cbff4b78e263ad729f0e4b179"

[[files]]
file = "config/jade/profiles/1/jade.json"
hash = "b78a0c24dc78612805066acb31be76e23423ae4a8392820aae1163fe90a47760"

[[files]]
file = "config/jade/profiles/2/jade.json"
hash = "470c98e9a24947a2eac8d5f6c1cf619840d2d93e6625b0557e80cfc7f3ad7fe6"

[[files]]
file = "config/jade/profiles/3/jade.json"
hash = "65ef88917bf7478cd42766b0394adda2b6837a130cdac74a948ee447c2309e0a"

[[files]]
file = "config/jade/server-plugin-overrides.json"
hash = "44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a"

[[files]]
file = "config/jade/sort-order.json"
hash = "c0235d429020dce0cd44eb11e34a728f83e8416ef5b61bd9607af370e963ad6c"

[[files]]
file = "config/lithium.properties"
hash = "6cf6f83720071fd1657c8e79b357caf68d40f410ae123e5f922483eb1d1d25be"

[[files]]
file = "config/modmenu.json"
hash = "16d20c40cc6c114faff5493b561873fe160a65047720bc19fb3a3dd64aa67f3b"

[[files]]
file = "config/peek/peek.properties"
hash = "59742cd9cc067a7f42b9a402096569a8d33029a0e304ead3b31f2a5975b5bd7d"

[[files]]
file = "config/sodium-fingerprint.json"
hash = "8e4857de7cb27f8f8627bf8b73db6de3c57717b62a21163c5764923345101d41"

[[files]]
file = "config/sodium-mixins.properties"
hash = "b627c4456e6fa0bc4b5f85e2f1cd949faedae3cb9afdaf2a5f52e6f3b6ae1f01"

[[files]]
file = "config/sodium-options.json"
hash = "0c34e9630f481e6af9dac31ca068ff3ec95f761d95b4385ff52d20d24b8f4411"

[[files]]
file = "config/transition.json"
hash = "6c0060c7301372bbc414f86a139b383e34fb620f0621badd71bb19efc3f26767"

[[files]]
file = "config/trender.json"
hash = "0a282f3623f7f9443a1d10b5768865f69e58b74e000dcfb4f40399626b7a6124"

[[files]]
file = "config/yacl.json5"
hash = "121b93764159be6fb7dab523b29a844e2bb78400ce8c48f52135a097e9b0006e"

[[files]]
file = "journeymap/config/6.0/journeymap.core.config"
hash = "c2015acad049d4aa879dce8bd56dbbfcf7042835ee4810a79f24c4d6173a602d"

[[files]]
file = "journeymap/config/6.0/journeymap.fullmap.config"
hash = "0009487a2336cd67fd8b1ead68941211398473df56b431d08aa35527a34a0977"

[[files]]
file = "journeymap/config/6.0/journeymap.minimap.config"
hash = "aadf7664be2d176f913534516e809eaceefc469893813371ec6035f2f3cd8ada"

[[files]]
file = "journeymap/config/6.0/journeymap.minimap2.config"
hash = "72f2a99309201c158e386e2d9b140d422854cd0410a2fa961daea736a42f488c"

[[files]]
file = "journeymap/config/6.0/journeymap.rendering.config"
hash = "59139373798af345188a9a11a0dd317ae39a5749d575cb0dbbfd481732c5caf7"

[[files]]
file = "journeymap/config/6.0/journeymap.topo.config"
hash = "2f6e8125fa9f35e0c700d49c908e0d60216d6d1cced17701351a174995570535"

[[files]]
file = "journeymap/config/6.0/journeymap.waypoint.config"
hash = "b531dddc06dcccca2741ffbea494fdf0525d67bde5a7e0d9d71c7468c5a1731a"

[[files]]
file = "journeymap/config/6.0/journeymap.webmap.config"
hash = "17fbf319709adeec6b71ead4ed0a2fc37210795257ab370c251ec36893c2253c"

[[files]]
file = "mods/appleskin.pw.toml"
hash = "de4779f316f62247e78c2594428a8ff5134bae55a2c329e1b6f7e853c2babb8a"
metafile = true

[[files]]
file = "mods/controlify.pw.toml"
hash = "b008f82e2e44de778ef082375e2f041ccffc17878e4c0ddca964f35629890952"
metafile = true

[[files]]
file = "mods/crash-assistant.pw.toml"
hash = "688283363bd049ee4cbd1416ca412d7e039ec5a5d86f6f690149ba12b3b2297b"
metafile = true

[[files]]
file = "mods/dynamic-crosshair.pw.toml"
hash = "1cfa10480536f3d3712bf11e8f7d12fc9e5b27000698eb33e78b12a1778456ad"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "2e1dbd715bdbf7c5ccc0f540db953df2952045ebae46f1b5c81521261c97784d"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "6adf5f512651c200a320219c32a3a51c8b95e219206f64b99cb93940d51b2cfa"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "4851e08949034729ae5e108626ea4dea2221a66d6428167fc75e1ed59245bc05"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "1aa94f817646eea69478dc3dce662c3f4b674359d7ce34cf58fd38dcbc56e458"
metafile = true

[[files]]
file = "mods/ferritecore-fabric.pw.toml"
hash = "c76d23f24d4318c25c08c5bb55057af752fa8f60bd7989fc95eb23a223ab8228"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "61222b46a3ba407bddb02bdd285766efd745da7a06ec78c425b8a45436ea8ebc"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "b7d33095f206cb34dc8cd3d5410a00597439a2fc793f4c158c7a2ecfc7e85e82"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "7f1cee180494aad48988b860135a9c3190420a7ec9deac616c307686a849bdea"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "51ae3f4d46495b8d433de22e26fcb6ed7e36e0f75c80293fea670ffba45a706a"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
hash = "ac7523674324f29f8c2189bc2076a94bcde8442bea2e68fbf1a29245e3e7cf97"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "d2827a2f8693193f30a6714a8e164e6a7b19bd5c0edccd0229cf4f4904182606"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "c66e4b3576440113259b5bae8d0660b8e0023ce852156f27383f8651ecc4bfe3"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "4a7720c5d70dad3b0cdc21d9ccdeeed98e1d727243520c781aeb37c6bf9c1558"
metafile = true

[[files]]
file = "mods/peek.pw.toml"
hash = "754b709ef984861d0db65e325077b5cac32721dddf2afb89103d3b290a813c2b"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "e674752dd4dd07c33d9b94f6e19c15ef893c356c3c5ed77aeaf35cf6d2325130"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "dd8c7eed10a3639d76595603142e1d18f6d26262747138c9442d70311006be5e"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "692b7f775360faf75015ef40d93ed1992c29214dc9a7df60da88b4b7bdb101f3"
metafile = true

[[files]]
file = "options.txt"
hash = "33f7179dc7f07dfa514a8899076680c592b746e1027be4a0399db8ad24a67fc1"

[[files]]
file = "resourcepacks/even-better-enchants.pw.toml"
hash = "26c0e4a143ee9c0aa5c257996a7efba141c30674f2b0209af5c263c36db555ea"
metafile = true

[[files]]
file = "resourcepacks/faithful-64x.pw.toml"
hash = "3091a2a3c616c19b256443c394bdb15bfe0dbd0179f4b5cad3d44eb01b80ab4a"
metafile = true

[[files]]
file = "resourcepacks/xekr-square-pattern.pw.toml"
hash = "ba6a2e0f07817808ad21b569da64af8ed33dd08e33c161f41a83ab64242e282f"
metafile = true

[[files]]
file = "shaderpacks/bliss-shader.pw.toml"
hash = "f27ca42de7b92a90cf387dbed38bbdb33013201a7cf5b2723a9830b3120634e0"
metafile = true

[[files]]
file = "shaderpacks/complementary-unbound.pw.toml"
hash = "006170836f3180d229a6b95e1b33c060d7afcd0755273669faf78e86f50579ed"
metafile = true
