name = "Vanilla Plus Plus"
author = "xinchen"
version = "1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7dc8585aea1e910e79062f1cfa064d05840f3d9afdb8ca416eeabb3ca0705051"

[versions]
fabric = "0.18.2"
minecraft = "1.21.11"

[options]
acceptable-game-versions = []
