hash-format = "sha256"

[[files]]
file = "config/appleskin.json5"
hash = "65edc28ca2bf6bd3e3684ae545fb74bcc0ec935a40d6ac60cb68c00c152e34fb"

[[files]]
file = "config/crash_assistant/config.toml"
hash = "755e6ee75977c54dc22a3631822cd8adc8b4b57b49776432f67b41c8043a67fa"

[[files]]
file = "config/crash_assistant/crash_assistant_localization_overrides/README.md"
hash = "52f394cd3754a29a6f236b1fe622bb430fa7e4632bce262eeb0333d71842bb52"

[[files]]
file = "config/crash_assistant/modlist.json"
hash = "4a6be59e11c56860e8a3499946c0aeec078c4c92178f6f35d9f42b26b34fa095"

[[files]]
file = "config/crash_assistant/problematic_mods_config.json"
hash = "989fb8f797a5a894f0cbf8bf529ac20c88cceee72384bdbeedd6a22d455199a3"

[[files]]
file = "config/dynamic_fps.json"
hash = "ca3d163bab055381827226140568f3bef7eaac187cebd76878e0b63e9e442356"

[[files]]
file = "config/dynamiccrosshair.json5"
hash = "99458f0109609cff4e0c6f3afb3ba474865784321f1d6625311dceb6ff55fae2"

[[files]]
file = "config/entityculling.json"
hash = "5110d83fa12df053d48eb3bcfded9d174e617910ce3e6c72f01dfc248c4e6abb"

[[files]]
file = "config/fabric/indigo-renderer.properties"
hash = "4b834d625f5e90a872297c248ad92d09c53b60a0cc8b11849b1b82be173ce5d2"

[[files]]
file = "config/ferritecore.mixin.properties"
hash = "a2091a291309db8920c8a80e913ed31c24c29687d8cd25ac18076ad85a90ddb8"

[[files]]
file = "config/inventoryprofilesnext/integrationHints/exampleIntegrationHints.json"
hash = "ca413dea02cce69c69dccdc525fb0ec013236876eff2d142772c68db3d772d3a"

[[files]]
file = "config/inventoryprofilesnext/inventoryprofiles.json"
hash = "3d0b10cb2ffcd8d24d9f719f2f0e9f6f40b11d31f6854e4a34a272fa59944872"

[[files]]
file = "config/iris-excluded.json"
hash = "4d3264b58c502afaeca3f44e8d2db0843c54b8ba957afd21a2d450fe10dafefb"

[[files]]
file = "config/iris.properties"
hash = "bcdad57b94a51caa3a31d81f1eaf8da7959ac790309c938adc57024c3dd8d2ca"

[[files]]
file = "config/jade/hide-blocks.json"
hash = "881bebe1f34ae249fc7d83f6a0d97ce3598746c133bc369775fc48fdeb5e1a76"

[[files]]
file = "config/jade/hide-entities.json"
hash = "4aa6e50e59ce75cc6e335e69ac98277f3d5afc1b016bb6c14aeece67a4ebb543"

[[files]]
file = "config/jade/hide-mob-effects.json"
hash = "a5c36f4ed48b1262f7f7d7be731c87c18aa6fdb79aaddb54568f9f8d526925c7"

[[files]]
file = "config/jade/jade.json"
hash = "c94f198c6ce5ccbe9e8eafb3e62b366294dd605cbff4b78e263ad729f0e4b179"

[[files]]
file = "config/jade/profiles/1/jade.json"
hash = "b78a0c24dc78612805066acb31be76e23423ae4a8392820aae1163fe90a47760"

[[files]]
file = "config/jade/profiles/2/jade.json"
hash = "470c98e9a24947a2eac8d5f6c1cf619840d2d93e6625b0557e80cfc7f3ad7fe6"

[[files]]
file = "config/jade/profiles/3/jade.json"
hash = "65ef88917bf7478cd42766b0394adda2b6837a130cdac74a948ee447c2309e0a"

[[files]]
file = "config/jade/server-plugin-overrides.json"
hash = "44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a"

[[files]]
file = "config/jade/sort-order.json"
hash = "c0235d429020dce0cd44eb11e34a728f83e8416ef5b61bd9607af370e963ad6c"

[[files]]
file = "config/lithium.properties"
hash = "6cf6f83720071fd1657c8e79b357caf68d40f410ae123e5f922483eb1d1d25be"

[[files]]
file = "config/modmenu.json"
hash = "16d20c40cc6c114faff5493b561873fe160a65047720bc19fb3a3dd64aa67f3b"

[[files]]
file = "config/peek/peek.properties"
hash = "59742cd9cc067a7f42b9a402096569a8d33029a0e304ead3b31f2a5975b5bd7d"

[[files]]
file = "config/sodium-fingerprint.json"
hash = "8e4857de7cb27f8f8627bf8b73db6de3c57717b62a21163c5764923345101d41"

[[files]]
file = "config/sodium-mixins.properties"
hash = "b627c4456e6fa0bc4b5f85e2f1cd949faedae3cb9afdaf2a5f52e6f3b6ae1f01"

[[files]]
file = "config/sodium-options.json"
hash = "0c34e9630f481e6af9dac31ca068ff3ec95f761d95b4385ff52d20d24b8f4411"

[[files]]
file = "config/transition.json"
hash = "6c0060c7301372bbc414f86a139b383e34fb620f0621badd71bb19efc3f26767"

[[files]]
file = "config/trender.json"
hash = "0a282f3623f7f9443a1d10b5768865f69e58b74e000dcfb4f40399626b7a6124"

[[files]]
file = "config/yacl.json5"
hash = "121b93764159be6fb7dab523b29a844e2bb78400ce8c48f52135a097e9b0006e"

[[files]]
file = "journeymap/config/6.0/journeymap.core.config"
hash = "c2015acad049d4aa879dce8bd56dbbfcf7042835ee4810a79f24c4d6173a602d"

[[files]]
file = "journeymap/config/6.0/journeymap.fullmap.config"
hash = "0009487a2336cd67fd8b1ead68941211398473df56b431d08aa35527a34a0977"

[[files]]
file = "journeymap/config/6.0/journeymap.minimap.config"
hash = "aadf7664be2d176f913534516e809eaceefc469893813371ec6035f2f3cd8ada"

[[files]]
file = "journeymap/config/6.0/journeymap.minimap2.config"
hash = "72f2a99309201c158e386e2d9b140d422854cd0410a2fa961daea736a42f488c"

[[files]]
file = "journeymap/config/6.0/journeymap.rendering.config"
hash = "59139373798af345188a9a11a0dd317ae39a5749d575cb0dbbfd481732c5caf7"

[[files]]
file = "journeymap/config/6.0/journeymap.topo.config"
hash = "2f6e8125fa9f35e0c700d49c908e0d60216d6d1cced17701351a174995570535"

[[files]]
file = "journeymap/config/6.0/journeymap.waypoint.config"
hash = "b531dddc06dcccca2741ffbea494fdf0525d67bde5a7e0d9d71c7468c5a1731a"

[[files]]
file = "journeymap/config/6.0/journeymap.webmap.config"
hash = "17fbf319709adeec6b71ead4ed0a2fc37210795257ab370c251ec36893c2253c"

[[files]]
file = "mods/appleskin.pw.toml"
hash = "ed50f3b3feba91fa31915aefb40690bc322f37be83490e6b59a443e83a46a542"
metafile = true

[[files]]
file = "mods/better-mount-hud.pw.toml"
hash = "6ef53c2c4e506e111b4bd7c1bc8804a5a7dcb2f6e3b79054575e73f6ce61ee94"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "d53b229a5588d33a8dac8682cba4371b22b2cbe2541c7129506cfbd44daaf6f8"
metafile = true

[[files]]
file = "mods/controlify.pw.toml"
hash = "ed52b5fefc66e11e9cc9d415748c7d9874c31868f91eea738fe9caf3557ac391"
metafile = true

[[files]]
file = "mods/crash-assistant.pw.toml"
hash = "9e4b7af4e25273baee0d9f2bc9f337d3b71ee52bbdd3d470cdcbb6d7876b1a1e"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "af8dc072b8d618de96260fccfa5fab7f79c5ca9679bc3a57473f6df4ce218fff"
metafile = true

[[files]]
file = "mods/dynamiccrosshair.pw.toml"
hash = "adcf2601fe44683e7b762d4f4874ed20299818b2e7eb926545903bb80e55524f"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "c23a1be7641341478b09c5c4f835b5e024a246f9e8521e92905bcab0d0e8cce0"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "39b4f43a271700276ff1ae632cf05f90b85f79670d955b50ced036e363a0efe9"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "61afd7af5c645ffd966b2bd86be944eacd1e48a8044e8f67082225d4d9989f0c"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "76a12a836d4c7f0f943a1e391dd2d7b5c4673caa497fff16593d49449376b117"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "93b2f668a96e7ef60f6bd15150d6dfc3b40e2c1504f5bcd79dfead63f866edfa"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "b7d33095f206cb34dc8cd3d5410a00597439a2fc793f4c158c7a2ecfc7e85e82"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "21caf1cc09d510a23284e704cb5211408085d5964e5d6ca129fc0dc175c8fb79"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "fa37926328b6b605cce3ca966e2b50af973a2d1043188da4599f105c2a430606"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
hash = "036576f257416774276edc60372a1265f28dd6bec765c72fef9aa9d164f2a148"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "0e87ab10adb3db84b1d6d2ce8bdd7158878b56c965055056b10ad6cde2634568"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "c66e4b3576440113259b5bae8d0660b8e0023ce852156f27383f8651ecc4bfe3"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "cd25851cbdaad2dd1957a8086ce54aa4bd3c45be75e1ba49168a54fafbd87898"
metafile = true

[[files]]
file = "mods/peek.pw.toml"
hash = "a7ed3b70eee552acb382d218b9ab840d6d8d81fac7491db9d146692c4d870389"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "e674752dd4dd07c33d9b94f6e19c15ef893c356c3c5ed77aeaf35cf6d2325130"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "dd8c7eed10a3639d76595603142e1d18f6d26262747138c9442d70311006be5e"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "6b2e6c4faa6fa928c5c5c582752b80401e418d4f897839b7d0338acc08e94803"
metafile = true

[[files]]
file = "options.txt"
hash = "9c8cb70f1393fc913c94c3f6a534a2df8040189a20cf0e27c94fa8ca38f7f4aa"

[[files]]
file = "resourcepacks/even-better-enchants.pw.toml"
hash = "26c0e4a143ee9c0aa5c257996a7efba141c30674f2b0209af5c263c36db555ea"
metafile = true

[[files]]
file = "resourcepacks/faithful-64x.pw.toml"
hash = "b372f716284513fd41fc72a9ac8e98db55eb9eb2d9c6c7b5638e8db863ecae80"
metafile = true

[[files]]
file = "resourcepacks/xekrsquarepattern.pw.toml"
hash = "f966c6105ad6dae12f96b235f46905a54f357eb5edfa162ad4f7bfa8eb30a108"
metafile = true

[[files]]
file = "resourcepacks/xk-redstone-display.pw.toml"
hash = "27750d59c2954e738be85531daf1f7b079d59de4973447b100d88b4fe2c6d1c5"
metafile = true

[[files]]
file = "shaderpacks/bliss-shader.pw.toml"
hash = "8ffd81a5e0b4c3bc2daf0d86714ef56df4beb1ed87a5c41c4e9bbb94a7006bc1"
metafile = true

[[files]]
file = "shaderpacks/complementary-unbound.pw.toml"
hash = "134b3cee2ac2b5c5b9d02d8d70e8e4ba32c7c241f5bc51209521831a7c254e22"
metafile = true
